services:
  main:
    container_name: zig-server
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - './:/var/www'
    ports:
      - '8080:8080'
    networks:
      - network
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  network:
    driver: bridge